export type RootStackParamList = {
    Intro: undefined;
    HomePage: undefined;
    SearchPage: undefined;
    ProfilePage: undefined;
    NotificationPage: undefined;
    BookList: { title: string, type: 'category' | 'author' | 'publisher' | 'new' | 'popular', id: string };
    BookListSearch: { title: string, type: 'search', keyword: string };
    SearchBook: undefined;
    HomeTabs: undefined;
    Category: undefined;
    FeedbackPage: undefined;
    BookDetail: { bookId: string };
    BorrowRecordDetailPage: { borrowRecordId: string };
    FineRecordDetail: { borrowRecordId: string | undefined };
    RenewalRequestPage: { borrowRecordId: string | undefined };
    Cart: { isDefault: boolean };
    BorrowRequest: { selectedBookIds: string[], selectDate?: string | null, dueDate?: string | null };
    HistoryBorrowRecord: undefined;
    HistoryFineRecord: undefined;
    HistoryFeedback: undefined;
    FeedbackDetail: { feedbackId: string };
};